name: devgiglio-admin-panel

services:
  admin-panel:
    image: ghcr.io/gipierogiglio-prog/admin-panel:latest
    container_name: devgiglio-admin-panel
    restart: always
    ports:
      - "5001:5001"
    networks:
      - devgiglio-network
    environment:
      - PORT=5001

networks:
  devgiglio-network:
    external: true
