const http = require('http');
const fs = require('fs');
const path = require('path');
const https = require('https');

const CF_TOKEN = process.env.CF_TOKEN || Buffer.from('Y2Z1dF9WNEhwNUhsY05CMk9WZms1T0RVQ25zSzJqQ2Z6Z1RNOVpZa2w0VmtOM2VhMjUyYzM=', 'base64').toString();
const ZONE_UK = '8c5417878f88d14a648711efd68b56e4';
const DIST = path.join(__dirname, 'frontend/dist');
const CONFIG_FILE = '/data/vpn-config.json';

const MIME = { '.html': 'text/html', '.js': 'application/javascript', '.css': 'text/css', '.png': 'image/png', '.svg': 'image/svg+xml', '.json': 'application/json' };

// Load VPN config (which domains are VPN-only vs public)
function loadConfig() {
  try {
    if (fs.existsSync(CONFIG_FILE)) {
      return JSON.parse(fs.readFileSync(CONFIG_FILE, 'utf-8'));
    }
  } catch(e) { /* ignore */ }
  return { vpnDomains: [], publicDomains: [] };
}

function saveConfig(cfg) {
  try {
    fs.mkdirSync(path.dirname(CONFIG_FILE), { recursive: true });
    fs.writeFileSync(CONFIG_FILE, JSON.stringify(cfg, null, 2));
    
    // Also generate a Traefik-compatible middleware config
    const traefikYaml = `# VPN Access Control - Generated by Dashboard
http:
  middlewares:
    vpn-only:
      ipWhiteList:
        sourceRange:
          - "10.0.0.0/24"
          - "127.0.0.1/32"
          - "172.16.0.0/12"
`;
    fs.writeFileSync('/data/traefik-vpn.yml', traefikYaml);
    
    return true;
  } catch(e) { return false; }
}

// Fetch domains from Cloudflare
function getDomains() {
  return new Promise((resolve, reject) => {
    if (!CF_TOKEN) return resolve([]);
    const u = new URL(`https://api.cloudflare.com/client/v4/zones/${ZONE_UK}/dns_records?per_page=50`);
    const opts = { hostname: u.hostname, path: u.pathname + u.search, headers: { 'Authorization': `Bearer ${CF_TOKEN}` } };
    https.get(opts, (res) => { let d=''; res.on('data',c=>d+=c); res.on('end',()=>{ try{ resolve(JSON.parse(d)); }catch(e){ reject(e); } }); }).on('error', reject);
  });
}

function serveStatic(url, res) {
  let filePath = url === '/' ? '/index.html' : url;
  const fullPath = path.join(DIST, filePath);
  if (!fullPath.startsWith(DIST)) { res.statusCode = 403; res.end(); return; }
  fs.readFile(fullPath, (err, data) => {
    if (err) { res.statusCode = 404; res.end('Not found'); return; }
    const ext = path.extname(filePath);
    res.setHeader('Content-Type', MIME[ext] || 'application/octet-stream');
    res.end(data);
  });
}

http.createServer((req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  const url = req.url.split('?')[0];
  
  // API: List domains with VPN status
  if (url === '/api/domains' && req.method === 'GET') {
    res.setHeader('Content-Type', 'application/json');
    getDomains().then(data => {
      const config = loadConfig();
      const vpnSet = new Set(config.vpnDomains || []);
      
      const domains = (data.result || []).filter(r => r.type === 'A').map(r => ({
        id: r.id,
        name: r.name,
        content: r.content,
        proxied: r.proxied,
        vpn: vpnSet.has(r.name)  // true = VPN-only, false = Public
      }));
      
      domains.push({ id: 'custom-dokploy', name: 'dokploy.devgiglio.com', content: '173.249.60.169', proxied: false, vpn: vpnSet.has('dokploy.devgiglio.com') });
      
      res.end(JSON.stringify({ domains: domains.sort((a, b) => a.name.localeCompare(b.name)), vpnDomains: config.vpnDomains || [], publicDomains: config.publicDomains || [] }));
    }).catch(e => { res.statusCode = 500; res.end(JSON.stringify({ error: e.message })); });
    return;
  }
  
  // API: Toggle VPN status for a domain
  if (url === '/api/domains/toggle' && req.method === 'POST') {
    let body = '';
    req.on('data', c => body += c);
    req.on('end', () => {
      try {
        const { name, vpn } = JSON.parse(body);
        const config = loadConfig();
        if (!config.vpnDomains) config.vpnDomains = [];
        if (!config.publicDomains) config.publicDomains = [];
        
        if (vpn) {
          // Make VPN-only: remove from public, add to vpn
          config.publicDomains = config.publicDomains.filter(d => d !== name);
          if (!config.vpnDomains.includes(name)) config.vpnDomains.push(name);
        } else {
          // Make public: remove from vpn, add to public
          config.vpnDomains = config.vpnDomains.filter(d => d !== name);
          if (!config.publicDomains.includes(name)) config.publicDomains.push(name);
        }
        
        saveConfig(config);
        res.setHeader('Content-Type', 'application/json');
        res.end(JSON.stringify({ success: true, vpn }));
      } catch(e) { res.statusCode = 400; res.end(JSON.stringify({ error: e.message })); }
    });
    return;
  }
  
  // API: Get VPN config summary
  if (url === '/api/config' && req.method === 'GET') {
    res.setHeader('Content-Type', 'application/json');
    res.end(JSON.stringify(loadConfig()));
    return;
  }
  
  // Serve the React frontend
  serveStatic(url, res);
}).listen(process.env.PORT || 3001, '0.0.0.0', () => console.log('[DASH] OK:' + (process.env.PORT || 3001)));
